Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using To_DoList_AspMVC.Data;
using To_DoList_AspMVC.Filters;
using To_DoList_AspMVC.Interfaces;
using To_DoList_AspMVC.Models;

namespace To_DoList_AspMVC.Controllers
{
    [SessionAuthorize]
    public class CategoriesController : Controller
    {
        // private readonly ApplicationDbContext _context;
        private readonly IRepository<Category> _repositoryCategory;
        public CategoriesController(IRepository<Category> repository)
        {
            _repositoryCategory = repository;
        }
        //public CategoriesController(ApplicationDbContext context)
        //{
        //    _context = context;
        //}

        public IActionResult Index()
        {
            //IEnumerable<Category> categories = _context.Categories.ToList();
            IEnumerable<Category> categories = _repositoryCategory.GetAll();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            //_context.Categories.Add(category);
            //_context.SaveChanges();
            _repositoryCategory.Add(category);
            return RedirectToAction("Index");
        }



        [HttpGet]
        public IActionResult Edit(string Uid)
        {
            //var category = _context.Categories.FirstOrDefault(e=>e.Uid == Uid);
            var category = _repositoryCategory.GetByUId(Uid);
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category , string Uid)
        {
            try
            {
                if (!ModelState.IsValid)
                {

                    return View(category);

                }
                //var cat = _context.Categories.FirstOrDefault(e => e.Uid == Uid);
                var cat = _repositoryCategory.GetByUId(Uid);
                if (cat != null)
                {
                    category.Name = cat.Name;
                    category.Description = cat.Description;
                    //_context.Categories.Update(cat);
                    //_context.SaveChanges();
                    _repositoryCategory.Update(category);
                    return RedirectToAction("Index");

                }
                return View(category);

            }
            catch (Exception ex)
            {
                return Content("حدث خطا  غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }







        [HttpGet]
        public IActionResult Delete(int Id)
        {
            //var category = _context.Categories.Find(Id);
            var category = _repositoryCategory.GetById(Id);
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Category category)
        {
            try
            {
                //_context.Categories.Remove(category);
                //_context.SaveChanges();
                _repositoryCategory.Delete(category.Id);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return Content("حدث خطا  غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }

    }
}

Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using To_DoList_AspMVC.Data;
using To_DoList_AspMVC.Filters;
using To_DoList_AspMVC.Models;

namespace To_DoList_AspMVC.Controllers
{
    [SessionAuthorize]
    public class ClientsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Client> clients = _context.Clients.Include(c => c.Nationality).ToList();
            return View(clients);
        }

        private void CreateTaskList()
        {
            var task = _context.TodoTasks.ToList();
            ViewBag.MyTasks = new SelectList(task, "Id", "Title");
        }


        private void CreateNationalityList()
        {
            var nati = _context.Nationalities.ToList();
            ViewBag.Nationalitys = new SelectList(nati, "Id", "Name_en");
        }


        public IActionResult TasksForClient(int id)
        {
            var client = _context.Clients
                .Include(c => c.MyTasks)
                .ThenInclude(t => t.Category) 
                .FirstOrDefault(c => c.Id == id);

            if (client == null)
                return NotFound();

            return View(client);
        }


        [HttpGet]
        public IActionResult Create()
        {
            CreateTaskList();
            CreateNationalityList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Client client)
        {
            if (!ModelState.IsValid)
            {
                CreateTaskList();
                CreateNationalityList();
                return View(client);
            }

            _context.Clients.Add(client);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }




        [HttpGet]
        public IActionResult Edit(string Uid)
        {
            var clients = _context.Clients.FirstOrDefault(e=>e.Uid == Uid);
            CreateTaskList();
            CreateNationalityList();
            return View(clients);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Client clients , string Uid)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    CreateNationalityList();
                    CreateTaskList();
                    return View(clients);

                }
                var cli = _context.Clients.FirstOrDefault(e => e.Uid == Uid);
                if (cli == null)
                {

                    clients.Name = cli.Name;
                    clients.Email = cli.Email;
                    _context.Clients.Update(cli);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
               return View(clients);

            }
            catch (Exception ex)
            {
                return Content("حدث خطا  غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }







        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var clients = _context.Clients.Find(Id);
            CreateTaskList();
            CreateNationalityList();
            return View(clients);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Client clients)
        {
            try
            {
                _context.Clients.Remove(clients);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return Content("حدث خطا  غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }
    }
}

Controllers/TodoTaskController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using To_DoList_AspMVC.Data;
using To_DoList_AspMVC.Filters;
using To_DoList_AspMVC.Models;

namespace To_DoList_AspMVC.Controllers
{
    [SessionAuthorize]
    public class TodoTaskController : Controller
    {

        private readonly ApplicationDbContext _context;

        public TodoTaskController(ApplicationDbContext context)
        {
            _context = context;
        }

     


        [HttpGet]
        public IActionResult Index()
        {
            try
            {

                IEnumerable<MyTask> myTasks = 
                    _context.TodoTasks
                    .Include(c => c.Category)
                    .Include(c => c.Client)
                    .Include(c => c.Priority)
                    .ToList();
                return View(myTasks);



            }
            catch (Exception ex)
            {

                return Content("حدث خطا  غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }

        private void createList()
        {
            IEnumerable<Category> category = _context.Categories.ToList();
            SelectList selectListItems = new SelectList(category, "Id", "Name");
            ViewBag.Categories = selectListItems;

            IEnumerable<Client> clients = _context.Clients.ToList();
            SelectList selectListItems2 = new SelectList(clients, "Id", "Name");
            ViewBag.Clients = selectListItems2;

            var nati = _context.Priorities.ToList();
            ViewBag.Priorities = new SelectList(nati, "Id", "Name");
        }


        [HttpGet]
        public IActionResult Create()
        {
            createList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(MyTask myTasks)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    createList();
                    return View(myTasks);

                }
                _context.TodoTasks.Add(myTasks);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return Content("حدث خطا  غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }






        [HttpGet]
        public IActionResult Edit(string Uid)
        {
            var myTasks = _context.TodoTasks.FirstOrDefault(e=>e.Uid==Uid);
            createList();
            return View(myTasks);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(MyTask myTasks, string Uid)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    createList();
                    return View(myTasks);

                }
                var Tas = _context.TodoTasks.FirstOrDefault(e => e.Uid == Uid);
                if (Tas != null)
                {
                    _context.TodoTasks.Update(Tas);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
               return View(myTasks);

            }
            catch (Exception ex)
            {
                return Content("حدث خطا  غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }







        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var myTasks = _context.TodoTasks.Find(Id);
            createList();
            return View(myTasks);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(MyTask myTasks)
        {
            try
            {
                _context.TodoTasks.Remove(myTasks);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return Content("حدث خطا  غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }



    }
}

Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - To_DoList_AspMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/To_DoList_AspMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">To_DoList_AspMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoTask" asp-action="Index">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Client</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - To_DoList_AspMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>